#!/usr/bin/env python3
"""Build a review file listing every inline comment that mentions a 6502/65C02
opcode mnemonic, organised so the user can scan and decide what to do.

Output goes to versions/anfs-4.21_variant_1/MNEMONIC-COMMENT-REVIEW.md.
"""

import re
from pathlib import Path

ROOT = Path("/Users/rjs/Code/acornaeology/acorn-nfs")
DRIVER = ROOT / "versions/anfs-4.21_variant_1/disassemble/disasm_anfs_421_variant_1.py"
OUT = ROOT / "versions/anfs-4.21_variant_1/MNEMONIC-COMMENT-REVIEW.md"

MNEM = sorted([
    'PHA','PHP','PHX','PHY','PLA','PLP','PLX','PLY',
    'TAX','TAY','TXA','TYA','TXS','TSX',
    'INX','INY','DEX','DEY','INC','DEC',
    'CLC','SEC','CLD','SED','CLI','SEI','CLV',
    'NOP','BIT','BRK','RTI','RTS','BRA','STZ',
    'ASL','LSR','ROL','ROR',
    'JMP','JSR',
    'AND','ORA','EOR','ADC','SBC','CMP','CPX','CPY',
    'LDA','LDX','LDY','STA','STX','STY',
    'BCC','BCS','BEQ','BNE','BMI','BPL','BVC','BVS',
    'TSB','TRB',
])
mnem_re = re.compile(r'\b(' + '|'.join(MNEM) + r')\b')
PREFIX_RE = re.compile(r'^([A-Z]{2,3})\s*--\s*(.*)$')

src = DRIVER.read_text()
LINE_RE = re.compile(
    r'^\s*comment\(0x([0-9A-Fa-f]+)\s*,\s*"([^"]*)"\s*,\s*inline=True\)\s*$',
    re.M,
)

prefix_rows = []   # (addr, mnemonic, tail, full_body)
mid_rows = []      # (addr, mnemonics_found, body)

for m in LINE_RE.finditer(src):
    addr = int(m.group(1), 16)
    body = m.group(2)
    if not mnem_re.search(body):
        continue
    pre = PREFIX_RE.match(body)
    if pre and pre.group(1) in MNEM:
        prefix_rows.append((addr, pre.group(1), pre.group(2).strip(), body))
    else:
        mnems_found = sorted(set(mnem_re.findall(body)))
        mid_rows.append((addr, mnems_found, body))

prefix_rows.sort(key=lambda r: r[0])
mid_rows.sort(key=lambda r: r[0])

with OUT.open("w") as f:
    f.write("# Inline comments mentioning a 6502 / 65C02 opcode mnemonic\n\n")
    f.write("Generated by `tools/build_mnemonic_review.py` for review and "
            "selective cleanup. The rendered .asm always shows the actual "
            "instruction on the same line as the inline comment, so re-stating "
            "the opcode in the comment text usually adds no information.\n\n")
    f.write("Use this file to walk every mention and decide:\n\n")
    f.write("- **Delete** if the comment is purely mechanical (just restates "
            "the opcode).\n")
    f.write("- **Trim** if there's a `MNEMONIC --` prefix but the rest is a "
            "real semantic remark.\n")
    f.write("- **Keep** if the mnemonic mention is structural context "
            "(`BIT-trick`, `INY before LDA`, etc.) where dropping it would "
            "lose information.\n\n")
    f.write(f"Total: {len(prefix_rows) + len(mid_rows)} comments "
            f"({len(prefix_rows)} prefix-style + {len(mid_rows)} mid-text).\n\n")

    f.write(f"## Prefix-style `MNEMONIC -- ...` ({len(prefix_rows)})\n\n")
    f.write("| Addr | Mnemonic | After `--` |\n")
    f.write("|---|---|---|\n")
    for addr, mnem, tail, _body in prefix_rows:
        # Escape | inside the comment body for table compatibility.
        safe_tail = tail.replace("|", r"\|")
        f.write(f"| `&{addr:04X}` | `{mnem}` | {safe_tail or '_(empty)_'} |\n")

    f.write(f"\n## Mid-text mentions ({len(mid_rows)})\n\n")
    f.write("| Addr | Mnemonic(s) | Comment body |\n")
    f.write("|---|---|---|\n")
    for addr, mnems, body in mid_rows:
        safe_body = body.replace("|", r"\|")
        mnem_list = " ".join(f"`{m}`" for m in mnems)
        f.write(f"| `&{addr:04X}` | {mnem_list} | {safe_body} |\n")

print(f"Wrote {OUT}")
print(f"  prefix-style: {len(prefix_rows)}")
print(f"  mid-text:     {len(mid_rows)}")
