#!/usr/bin/env python3
"""Compare semantic labels across NFS ROM disassembly versions for consistency.

Extracts label(), subroutine(), and hook_subroutine() calls from each driver
script, filters out auto-generated py8dis labels, and reports inconsistencies
where the same routine/location has different names in different versions.
"""

import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

BASE_DIR = Path(subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True).strip())

SCRIPTS = {
    "3.34": BASE_DIR / "versions" / "3.34" / "disassemble" / "disasm_nfs_334.py",
    "3.34B": BASE_DIR / "versions" / "3.34B" / "disassemble" / "disasm_nfs_334b.py",
    "3.35D": BASE_DIR / "versions" / "3.35D" / "disassemble" / "disasm_nfs_335d.py",
}

# Relocated code runtime address ranges (same across all versions)
RELOCATED_RANGES = [
    (0x0016, 0x0076),  # BRK handler + NMI workspace
    (0x0400, 0x04FF),  # Page 4
    (0x0500, 0x05FF),  # Page 5
    (0x0600, 0x06FF),  # Page 6
]

# 3.34 -> 3.34B address shift boundary
SHIFT_BOUNDARY_334_TO_334B = 0x81C8

# Econet layer boundary (no shift from 3.34 to 3.34B)
ECONET_BOUNDARY = 0x964C


def is_relocated(addr):
    """Check if address falls in a relocated code block."""
    for lo, hi in RELOCATED_RANGES:
        if lo <= addr <= hi:
            return True
    return False


def is_auto_label(name):
    """Check if a label name is auto-generated by py8dis."""
    # Auto address labels: cXXXX (4+ hex digits, no meaningful prefix)
    if re.match(r'^c[0-9a-fA-F]{4,}$', name):
        return True
    # Auto loop labels: loop_cXXXX
    if re.match(r'^loop_c[0-9a-fA-F]{4,}$', name):
        return True
    # Auto return labels: return_N
    if re.match(r'^return_\d+$', name):
        return True
    # Single-letter labels
    if len(name) == 1:
        return True
    return False


def extract_labels(filepath):
    """Extract all label-creating calls from a driver script.

    Returns dict of {address: name} for semantic (non-auto) labels.
    """
    text = filepath.read_text()
    labels = {}

    # Match label(0xNNNN, "name") — address can be 0xNN, 0xNNNN, or 0x00NN
    for m in re.finditer(
        r'^\s*label\(\s*(0x[0-9a-fA-F]+)\s*,\s*"([^"]+)"', text, re.MULTILINE
    ):
        addr = int(m.group(1), 16)
        name = m.group(2)
        if not is_auto_label(name):
            labels[addr] = name

    # Match subroutine(0xNNNN, "name", ...) — name is the second argument
    for m in re.finditer(
        r'^\s*subroutine\(\s*(0x[0-9a-fA-F]+)\s*,\s*"([^"]+)"', text, re.MULTILINE
    ):
        addr = int(m.group(1), 16)
        name = m.group(2)
        if not is_auto_label(name):
            labels[addr] = name

    # Match hook_subroutine(0xNNNN, "name", ...)
    for m in re.finditer(
        r'^\s*hook_subroutine\(\s*(0x[0-9a-fA-F]+)\s*,\s*"([^"]+)"',
        text,
        re.MULTILINE,
    ):
        addr = int(m.group(1), 16)
        name = m.group(2)
        if not is_auto_label(name):
            labels[addr] = name

    return labels


def map_334_to_334b(addr):
    """Map a 3.34 ROM address to its 3.34B equivalent.

    Below &81C8: identical.
    &81C8-&964A: shift +1 (version string insertion).
    &964C-&9FFF: identical (econet layer).
    Relocated code: identical runtime addresses.
    """
    if is_relocated(addr):
        return addr
    if addr < SHIFT_BOUNDARY_334_TO_334B:
        return addr
    if addr >= ECONET_BOUNDARY:
        return addr
    # In the shifted region: 3.34B = 3.34 + 1
    return addr + 1


def map_334b_to_334(addr):
    """Reverse mapping: 3.34B ROM address to 3.34 equivalent."""
    if is_relocated(addr):
        return addr
    if addr < SHIFT_BOUNDARY_334_TO_334B:
        return addr
    if addr >= ECONET_BOUNDARY:
        return addr
    return addr - 1


def build_334b_to_335d_mapping(labels_334b, labels_335d):
    """Build address mapping from 3.34B to 3.35D using shared label names.

    Labels present in both versions with the same name establish correspondence.
    Returns two dicts: forward (334B->335D) and reverse (335D->334B).
    """
    # Invert labels_335d: name -> addr
    name_to_addr_335d = {}
    for addr, name in labels_335d.items():
        name_to_addr_335d[name] = addr

    forward = {}  # 334B addr -> 335D addr
    reverse = {}  # 335D addr -> 334B addr

    for addr_334b, name in labels_334b.items():
        if name in name_to_addr_335d:
            addr_335d = name_to_addr_335d[name]
            forward[addr_334b] = addr_335d
            reverse[addr_335d] = addr_334b

    return forward, reverse


def format_addr(addr):
    """Format an address in Acorn hex notation."""
    return f"&{addr:04X}"


def compare_pair(labels_a, labels_b, name_a, name_b, map_a_to_b, map_b_to_a):
    """Compare labels between two versions using address mapping.

    Returns list of (addr_a, addr_b, name_a_label, name_b_label, issue_type) tuples.
    """
    issues = []

    # Check each label in version A against version B
    for addr_a, label_a in sorted(labels_a.items()):
        addr_b = map_a_to_b(addr_a)
        if addr_b is None:
            continue
        if addr_b in labels_b:
            label_b = labels_b[addr_b]
            if label_a != label_b:
                issues.append((addr_a, addr_b, label_a, label_b, "different"))
        else:
            issues.append((addr_a, addr_b, label_a, None, "missing_in_b"))

    # Check labels in B that have no counterpart in A
    for addr_b, label_b in sorted(labels_b.items()):
        addr_a = map_b_to_a(addr_b)
        if addr_a is None:
            continue
        if addr_a not in labels_a:
            issues.append((addr_a, addr_b, None, label_b, "missing_in_a"))

    return issues


def main():
    # Extract labels from all three versions
    all_labels = {}
    for version, script_filepath in SCRIPTS.items():
        if not script_filepath.exists():
            print(f"Warning: {script_filepath} not found, skipping {version}")
            continue
        all_labels[version] = extract_labels(script_filepath)
        print(f"{version}: {len(all_labels[version])} semantic labels extracted")

    if len(all_labels) < 2:
        print("Need at least 2 versions to compare.")
        sys.exit(1)

    print()

    # Build 3.34B -> 3.35D mapping from shared labels
    map_334b_335d_fwd = {}
    map_334b_335d_rev = {}
    if "3.34B" in all_labels and "3.35D" in all_labels:
        map_334b_335d_fwd, map_334b_335d_rev = build_334b_to_335d_mapping(
            all_labels["3.34B"], all_labels["3.35D"]
        )
        print(
            f"3.34B <-> 3.35D: {len(map_334b_335d_fwd)} shared labels "
            f"establish address correspondence"
        )
        print()

    # Also build 3.34 -> 3.35D via chained mapping
    # and a direct shared-name mapping for 3.34 <-> 3.35D
    map_334_335d_fwd = {}
    map_334_335d_rev = {}
    if "3.34" in all_labels and "3.35D" in all_labels:
        map_334_335d_fwd, map_334_335d_rev = build_334b_to_335d_mapping(
            all_labels["3.34"], all_labels["3.35D"]
        )
        print(
            f"3.34 <-> 3.35D: {len(map_334_335d_fwd)} shared labels "
            f"establish address correspondence"
        )
        print()

    # ================================================================
    # Compare 3.34 vs 3.34B (known +1 shift)
    # ================================================================
    if "3.34" in all_labels and "3.34B" in all_labels:
        print("=" * 78)
        print("COMPARISON: 3.34 vs 3.34B (known +1 shift above &81C8)")
        print("=" * 78)

        issues = compare_pair(
            all_labels["3.34"],
            all_labels["3.34B"],
            "3.34",
            "3.34B",
            map_334_to_334b,
            map_334b_to_334,
        )

        different = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "different"]
        missing_b = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "missing_in_b"]
        missing_a = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "missing_in_a"]

        if different:
            print(f"\nDIFFERENT NAMES ({len(different)}):")
            print("-" * 78)
            for addr_a, addr_b, label_a, label_b, _ in sorted(different):
                print(
                    f"  {format_addr(addr_a)} (3.34) / {format_addr(addr_b)} (3.34B): "
                    f"{label_a!r} vs {label_b!r}"
                )

        if missing_b:
            print(f"\nMISSING IN 3.34B ({len(missing_b)}):")
            print("-" * 78)
            for addr_a, addr_b, label_a, _, _ in sorted(missing_b):
                print(
                    f"  {format_addr(addr_a)} (3.34): {label_a!r} "
                    f"-> {format_addr(addr_b)} (3.34B): no label"
                )

        if missing_a:
            print(f"\nMISSING IN 3.34 ({len(missing_a)}):")
            print("-" * 78)
            for addr_a, addr_b, _, label_b, _ in sorted(missing_a):
                print(
                    f"  {format_addr(addr_b)} (3.34B): {label_b!r} "
                    f"-> {format_addr(addr_a)} (3.34): no label"
                )

        if not different and not missing_b and not missing_a:
            print("\n  No inconsistencies found.")

        print()

    # ================================================================
    # Compare 3.34B vs 3.35D (non-uniform mapping)
    # ================================================================
    if "3.34B" in all_labels and "3.35D" in all_labels:
        print("=" * 78)
        print("COMPARISON: 3.34B vs 3.35D (non-uniform mapping via shared labels)")
        print("=" * 78)

        def map_334b_to_335d(addr):
            return map_334b_335d_fwd.get(addr)

        def map_335d_to_334b(addr):
            return map_334b_335d_rev.get(addr)

        issues = compare_pair(
            all_labels["3.34B"],
            all_labels["3.35D"],
            "3.34B",
            "3.35D",
            map_334b_to_335d,
            map_335d_to_334b,
        )

        different = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "different"]
        missing_b = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "missing_in_b"]
        missing_a = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "missing_in_a"]

        if different:
            print(f"\nDIFFERENT NAMES ({len(different)}):")
            print("-" * 78)
            for addr_a, addr_b, label_a, label_b, _ in sorted(different):
                print(
                    f"  {format_addr(addr_a)} (3.34B) / {format_addr(addr_b)} (3.35D): "
                    f"{label_a!r} vs {label_b!r}"
                )

        # For 3.34B vs 3.35D, only report missing labels where we have a
        # mapping (shared-name mapping means by definition shared labels match,
        # so "missing" only shows up for addresses NOT in the mapping).
        # Instead, report labels unique to each version.
        unique_334b = set()
        unique_335d = set()
        for addr, name in all_labels["3.34B"].items():
            if addr not in map_334b_335d_fwd:
                unique_334b.add((addr, name))
        for addr, name in all_labels["3.35D"].items():
            if addr not in map_334b_335d_rev:
                unique_335d.add((addr, name))

        if unique_334b:
            print(f"\nLABELS ONLY IN 3.34B (no matching label in 3.35D) ({len(unique_334b)}):")
            print("-" * 78)
            for addr, name in sorted(unique_334b):
                print(f"  {format_addr(addr)}: {name!r}")

        if unique_335d:
            print(f"\nLABELS ONLY IN 3.35D (no matching label in 3.34B) ({len(unique_335d)}):")
            print("-" * 78)
            for addr, name in sorted(unique_335d):
                print(f"  {format_addr(addr)}: {name!r}")

        if not different and not unique_334b and not unique_335d:
            print("\n  No inconsistencies found.")

        print()

    # ================================================================
    # Compare 3.34 vs 3.35D (non-uniform mapping)
    # ================================================================
    if "3.34" in all_labels and "3.35D" in all_labels:
        print("=" * 78)
        print("COMPARISON: 3.34 vs 3.35D (non-uniform mapping via shared labels)")
        print("=" * 78)

        def map_334_to_335d(addr):
            return map_334_335d_fwd.get(addr)

        def map_335d_to_334(addr):
            return map_334_335d_rev.get(addr)

        issues = compare_pair(
            all_labels["3.34"],
            all_labels["3.35D"],
            "3.34",
            "3.35D",
            map_334_to_335d,
            map_335d_to_334,
        )

        different = [(a, b, la, lb, t) for a, b, la, lb, t in issues if t == "different"]

        if different:
            print(f"\nDIFFERENT NAMES ({len(different)}):")
            print("-" * 78)
            for addr_a, addr_b, label_a, label_b, _ in sorted(different):
                print(
                    f"  {format_addr(addr_a)} (3.34) / {format_addr(addr_b)} (3.35D): "
                    f"{label_a!r} vs {label_b!r}"
                )

        # Labels unique to each version (not in the other via shared-name mapping)
        unique_334 = set()
        unique_335d = set()
        for addr, name in all_labels["3.34"].items():
            if addr not in map_334_335d_fwd:
                unique_334.add((addr, name))
        for addr, name in all_labels["3.35D"].items():
            if addr not in map_334_335d_rev:
                unique_335d.add((addr, name))

        if unique_334:
            print(f"\nLABELS ONLY IN 3.34 (no matching label in 3.35D) ({len(unique_334)}):")
            print("-" * 78)
            for addr, name in sorted(unique_334):
                print(f"  {format_addr(addr)}: {name!r}")

        if unique_335d:
            print(f"\nLABELS ONLY IN 3.35D (no matching label in 3.34) ({len(unique_335d)}):")
            print("-" * 78)
            for addr, name in sorted(unique_335d):
                print(f"  {format_addr(addr)}: {name!r}")

        if not different and not unique_334 and not unique_335d:
            print("\n  No inconsistencies found.")

        print()

    # ================================================================
    # Special check: Tube register labels
    # ================================================================
    print("=" * 78)
    print("SPECIAL CHECK: Tube register labels at &0527")
    print("=" * 78)
    for version in ["3.34", "3.34B", "3.35D"]:
        if version in all_labels and 0x0527 in all_labels[version]:
            print(f"  {version}: {all_labels[version][0x0527]!r}")
        elif version in all_labels:
            print(f"  {version}: no label at &0527")
    print()
    print("Expected: 3.34=tube_poll_r1_wrch, 3.34B=tube_poll_r4_wrch, "
          "3.35D=tube_poll_r1_wrch")
    tube_335d = all_labels.get("3.35D", {}).get(0x0527, "")
    if tube_335d == "tube_poll_r4_wrch":
        print("  -> INCONSISTENCY: 3.35D has 'tube_poll_r4_wrch' but should have "
              "'tube_poll_r1_wrch' (reverted to R1)")
    elif tube_335d == "tube_poll_r1_wrch":
        print("  -> OK: 3.35D correctly uses 'tube_poll_r1_wrch'")
    print()

    # ================================================================
    # Three-way consistency: labels present in all three versions
    # ================================================================
    if len(all_labels) == 3:
        print("=" * 78)
        print("THREE-WAY CONSISTENCY CHECK")
        print("=" * 78)

        # Collect all label names across versions
        all_names = set()
        for version_labels in all_labels.values():
            all_names.update(version_labels.values())

        # For each name, find which versions have it and at what address
        name_versions = {}
        for name in sorted(all_names):
            name_versions[name] = {}
            for version, version_labels in all_labels.items():
                for addr, lname in version_labels.items():
                    if lname == name:
                        name_versions[name][version] = addr

        # Report names that appear in exactly 2 of 3 versions
        partial = {
            name: versions
            for name, versions in name_versions.items()
            if len(versions) == 2
        }

        if partial:
            print(f"\nLabels present in exactly 2 of 3 versions ({len(partial)}):")
            print("-" * 78)
            for name in sorted(partial):
                versions = partial[name]
                present = ", ".join(
                    f"{v} @ {format_addr(a)}" for v, a in sorted(versions.items())
                )
                missing = [v for v in ["3.34", "3.34B", "3.35D"] if v not in versions]
                print(f"  {name!r}: present in {present}; missing in {', '.join(missing)}")
        else:
            print("\n  All shared labels appear in either 1 or all 3 versions.")

        # Report names present in only 1 version (truly unique)
        unique = {
            name: versions
            for name, versions in name_versions.items()
            if len(versions) == 1
        }
        if unique:
            print(f"\nLabels unique to a single version ({len(unique)}):")
            print("-" * 78)
            for name in sorted(unique):
                version, addr = next(iter(unique[name].items()))
                print(f"  {name!r}: only in {version} @ {format_addr(addr)}")

        print()


if __name__ == "__main__":
    main()
